[package]
name = "dbd-bloodpoint-spender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autopilot = "0.4.0"
image = "0.22.4"
tokio = { version = "1.24.2", features = ["full"] }
